apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cnap-argo
  name: cnap-argo
  namespace: cnap-argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnap-argo
  strategy: {}
  template:
    metadata:
      labels:
        app: cnap-argo
    spec:
      containers:
      - image: quay.io/redhatworkshops/cnap-argo:latest
        name: cnap-argo
        env:
        - name: COLOR
          value: "blue"
        resources: {}