apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cnap-argo
  name: cnap-argo
  namespace: cnap-argo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cnap-argo